class AddColumnsToPatients < ActiveRecord::Migration[5.2]
  def change
    add_column :patients, :wake_of_bed, :integer
    add_column :patients, :sleep_all_nigth, :integer
    add_column :patients, :turn_bed, :integer
    add_column :patients, :car_ride, :integer
    add_column :patients, :stand_up_half_and_hour, :integer
    add_column :patients, :sit_down_chair, :integer
    add_column :patients, :climbing_stairs, :integer
    add_column :patients, :walk_meters, :integer
    add_column :patients, :walk_kilometers, :integer
    add_column :patients, :high_shelves, :integer
    add_column :patients, :throw_ball, :integer
    add_column :patients, :run_one_block, :integer
    add_column :patients, :food_refrigerator, :integer
    add_column :patients, :make_bed, :integer
    add_column :patients, :socks, :integer
    add_column :patients, :clean_bathtub, :integer
    add_column :patients, :move_chair, :integer
    add_column :patients, :heavy_doors, :integer
    add_column :patients, :carry_bags, :integer
    add_column :patients, :heavy_suitcase, :integer
    add_column :patients, :sadness, :integer
    add_column :patients, :pessimism, :integer
    add_column :patients, :failure, :integer
    add_column :patients, :loss_of_pleasure, :integer
    add_column :patients, :feelings_of_guilt, :integer
    add_column :patients, :feelings_of_punisment, :integer
    add_column :patients, :dissatisfaction_with_oneself, :integer
    add_column :patients, :self_criticism, :integer
    add_column :patients, :suicidal_thoughts, :integer
    add_column :patients, :crying, :integer
    add_column :patients, :agitation, :integer
    add_column :patients, :loss_of_interest, :integer
    add_column :patients, :indecisions, :integer
    add_column :patients, :devaluation, :integer
    add_column :patients, :loss_of_energy, :integer
    add_column :patients, :sleep_changes, :integer
    add_column :patients, :irritability, :integer
    add_column :patients, :appetite_changes, :integer
    add_column :patients, :difficult_to_focus, :integer
    add_column :patients, :fatigue, :integer
    add_column :patients, :change_sexual_interest, :integer
    add_column :patients, :sigo_viviendo, :integer
    add_column :patients, :mi_vida_va_bien, :integer
    add_column :patients, :es_bueno_dolor, :integer
    add_column :patients, :sacrificaria_con_gusto, :integer
    add_column :patients, :no_es_necesario, :integer
    add_column :patients, :aunque_las_cosas, :integer
    add_column :patients, :necesito_concentrarme, :integer
    add_column :patients, :hago_muchas_actividades, :integer
    add_column :patients, :llevo_una_vida, :integer
    add_column :patients, :controlar_mi_dolor, :integer
    add_column :patients, :mis_pensamientos, :integer
    add_column :patients, :a_pesar_del_dolor, :integer
    add_column :patients, :mantener_el_nivel, :integer
    add_column :patients, :antes_de_hacer, :integer
    add_column :patients, :cuando_mi_dolor, :integer
    add_column :patients, :tendre_control, :integer
    add_column :patients, :evito_situaciones, :integer
    add_column :patients, :mis_preocupaciones, :integer
    add_column :patients, :es_un_alivio, :integer
    add_column :patients, :tengo_que_luchar, :integer
    add_column :patients, :intensidad_dolor, :integer
    add_column :patients, :estar_pie, :integer
    add_column :patients, :cuidados_personales, :integer
    add_column :patients, :dormir, :integer
    add_column :patients, :levantar_peso, :integer
    add_column :patients, :actividad_sexual, :integer
    add_column :patients, :andar, :integer
    add_column :patients, :vida_social, :integer
    add_column :patients, :estar_sentado, :integer
    add_column :patients, :viajar, :integer
  end
end
